import { NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'
import { generateQRSvg } from '@/lib/qr/generate'

export async function GET() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: userData } = await supabase
    .from('users').select('tenant_id').eq('id', user.id).single()
  if (!userData) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const { data, error } = await supabase
    .from('campaigns')
    .select('*, product:products(*), promotion:promotions(*)')
    .eq('tenant_id', userData.tenant_id)
    .order('created_at', { ascending: false })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ data })
}

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: userData } = await supabase
    .from('users')
    .select('tenant_id, tenant:tenants(brand_color, max_campaigns, plan)')
    .eq('id', user.id).single()
  if (!userData) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const tenant = userData.tenant as { brand_color: string; max_campaigns: number; plan: string } | null

  // Check campaign limit
  const { count } = await supabase
    .from('campaigns')
    .select('*', { count: 'exact', head: true })
    .eq('tenant_id', userData.tenant_id)

  if ((count ?? 0) >= (tenant?.max_campaigns ?? 1) && (tenant?.max_campaigns ?? 1) !== 999999) {
    return NextResponse.json({ error: 'Campaign limit reached. Please upgrade your plan.' }, { status: 403 })
  }

  const body = await request.json()
  const {
    name, product_id, promotion_id,
    require_order_verify, smart_routing, smart_routing_threshold,
    language, review_url, custom_thank_you_msg,
    custom_color, custom_logo_url,
  } = body

  if (!name || !product_id) {
    return NextResponse.json({ error: 'name and product_id are required' }, { status: 400 })
  }

  // 1. Insert campaign (short_code auto-generated by DB trigger)
  const serviceClient = createServiceClient()
  const { data: campaign, error: insertError } = await serviceClient
    .from('campaigns')
    .insert({
      tenant_id: userData.tenant_id,
      name,
      product_id,
      promotion_id: promotion_id || null,
      status: 'active',
      require_order_verify: require_order_verify ?? true,
      smart_routing: smart_routing ?? true,
      smart_routing_threshold: smart_routing_threshold ?? 4,
      language: language ?? 'en',
      review_url: review_url || null,
      custom_thank_you_msg: custom_thank_you_msg || null,
      custom_color: custom_color || null,
      custom_logo_url: custom_logo_url || null,
    })
    .select()
    .single()

  if (insertError || !campaign) {
    return NextResponse.json({ error: insertError?.message ?? 'Failed to create campaign' }, { status: 500 })
  }

  // 2. Generate QR SVG with brand color
  const brandColor = custom_color ?? tenant?.brand_color ?? '#6366f1'
  try {
    const qrSvg = await generateQRSvg({ shortCode: campaign.qr_short_code, color: brandColor })
    // Store QR as data URI on the campaign
    const qrDataUri = `data:image/svg+xml;base64,${Buffer.from(qrSvg).toString('base64')}`
    await serviceClient
      .from('campaigns')
      .update({ qr_code_url: qrDataUri })
      .eq('id', campaign.id)
    campaign.qr_code_url = qrDataUri
  } catch (qrError) {
    console.error('QR generation failed:', qrError)
    // Non-fatal — campaign still created
  }

  return NextResponse.json({ data: campaign }, { status: 201 })
}
